server:
  port: 8762


spring:
  zipkin:
    base-url: http://localhost:9411

#  rabbitmq:
#    host: localhost
#    port: 5672
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys-user?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: 114.67.80.70
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    publisher-returns: true
    template:
       #开启mandatory: true, basic.return方法将消息返还给生产者
       mandatory: true
    listener:
       simple:
           #手动ACK
           acknowledge-mode: manual
           default-requeue-rejected: false
           concurrency: 1
           max-concurrency: 1
           prefetch: 1
           retry:
              enabled: true

    virtual-host: /

foo: foo version 1